### ISSUE TITLE
Spotify File Looks Good

### ISSUE THREAD

**Issue by jlag34** [haldunanil/jammming#1]
Good job on building the functionality of your Spotify.js file. It is definitely the hardest part of the project and I am glad you were able to get through it. The file has a lot of comments which is great. My biggest problem is that the indentation is off. Try installing a `prettify` plugin for your text editor so that it will auto indent for you. Otherwise great job in this file.

**Comment by haldunanil** [comment]
Thanks Joe, fixed the indentation per commit #b912467
