### ISSUE TITLE
App File Built Correctly

### ISSUE THREAD

**Issue by jlag34** [haldunanil/jammming#2]
Looking over your App file it seems that you did everything right. The methods are all spot on and state is never mutated. A good instance is when you use `concat` on line 31:

```
let newPlaylist = this.state.playlistTracks.concat(track);
```

This is great because you aren’t mutating state. Some might use `push` here, which is bad. Overall, great job.

**Comment by haldunanil** [comment]
Thanks Joe, I may have attempted `push` initially and seen the light with concat :)
