### ISSUE TITLE
Summary - Exceeds Expectations

### ISSUE THREAD

**Issue by jlag34** [haldunanil/jammming#6]
This project was a pleasure to review. There were plenty of comments and you code was very clean. You passed down props correctly throughout your entire project. Another thing is that you had functions in the correct components. You also kept your main component logic in the parent components so that it could be passed down. Lastly, you were able to follow the directions perfectly which lead to a very nice final product. My only concern is your indentation, check your text editor settings. Altogether, you did a really great job.

**Comment by haldunanil** [comment]
Thanks Joe, it was fun working through this project. Really appreciate your comments!
